markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://dssysway.github.io
author: ftom
highlighter: pygments
safe: true
paginate: 16
gems: [jekyll-paginate]
highlighter: pygments
mardown: redcarpet
baidu-analysis: 1f7dbc7243064c6e1a294bd85b50f754

